ITEM.name = "Large Box of 12.7mm"
ITEM.height = 2
ITEM.width = 2
ITEM.model = "models/props/cs_office/cardboard_box03.mdl"
ITEM.ammo = "gr_127mm" -- type of the ammo
ITEM.ammoAmount = 120 -- amount of the ammo
ITEM.description = "A Box that contains 120 rounds of 12.7mm ammo."
ITEM.price = 325
ITEM.flag = "f"