ITEM.name = "Large Box of .308"
ITEM.height = 2
ITEM.width = 2
ITEM.model = "models/props/cs_office/cardboard_box03.mdl"
ITEM.ammo = "gr_308" -- type of the ammo
ITEM.ammoAmount = 120 -- amount of the ammo
ITEM.description = "A Box that contains 120 rounds of .308 ammo."
ITEM.price = 200
ITEM.flag = "f"