ITEM.name = "Large Box of Microfusion Cells"
ITEM.height = 2
ITEM.width = 2
ITEM.model = "models/props/cs_office/cardboard_box03.mdl"
ITEM.ammo = "gr_mfc" -- type of the ammo
ITEM.ammoAmount = 180 -- amount of the ammo
ITEM.description = "A Box that contains 180 charges of MFC" 
ITEM.price = 325
ITEM.flag = "f"