ITEM.name = "Large Box of .38"
ITEM.model = "models/props/cs_office/cardboard_box03.mdl"
ITEM.height = 2
ITEM.width = 2
ITEM.ammo = "tfa_38_ammo" -- type of the ammo
ITEM.ammoAmount = 180 -- amount of the ammo
ITEM.description = "A Box that contains 180 rounds of .38 ammo."
ITEM.price = 125
ITEM.flag = "f"