ITEM.name = "Large Box of .357"
ITEM.height = 2
ITEM.width = 2
ITEM.model = "models/props/cs_office/cardboard_box03.mdl"
ITEM.ammo = "item_ammo_357" -- type of the ammo
ITEM.ammoAmount = 144 -- amount of the ammo
ITEM.description = "A Box that contains 144 rounds of .357 ammo."
ITEM.price = 200
ITEM.flag = "f"