ITEM.name = "Large Box of 12g"
ITEM.model = "models/props/cs_office/cardboard_box03.mdl"
ITEM.height = 2
ITEM.width = 2
ITEM.ammo = "gr_12g" -- type of the ammo
ITEM.ammoAmount = 144 -- amount of the ammo
ITEM.description = "A Box that contains a total of 144 12g shells."
ITEM.price = 125
ITEM.flag = "f"